const FETCH_BEACHES = "FETCH_BEACHES";
const FETCH_BEACH = "FETCH_BEACH";
const UNSET_BEACH = "UNSET_BEACH";
const MARK_BEACH = "MARK_BEACH";
const ADD_PHOTO = "ADD_PHOTO";

export { FETCH_BEACHES, FETCH_BEACH, UNSET_BEACH, MARK_BEACH, ADD_PHOTO };
