const ADD_PHOTO = "ADD_PHOTO";
const FETCH_VISITED = "FETCH_VISITED";
const FETCH_WISHLIST = "FETCH_WISHLIST";
const UNSET_USER_BEACH = "UNSET_USER_BEACH";

export { ADD_PHOTO, FETCH_VISITED, FETCH_WISHLIST, UNSET_USER_BEACH };
